// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCY4lqczWXyU7v1Nm1PuO9elNkPqyBdM5M',
    appId: '1:292351751315:web:0aba29baffc189e1dd4966',
    messagingSenderId: '292351751315',
    projectId: 'aha-project-management',
    authDomain: 'aha-project-management.firebaseapp.com',
    storageBucket: 'aha-project-management.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHH7SR6mqY6Di3Mle5EedAeO5gp9e-iGI',
    appId: '1:292351751315:android:1b617aaffed38544dd4966',
    messagingSenderId: '292351751315',
    projectId: 'aha-project-management',
    storageBucket: 'aha-project-management.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBK9cx_j9NAZwib-81_lwJz0qU-8-y27cc',
    appId: '1:292351751315:ios:c7ead44efafcbc46dd4966',
    messagingSenderId: '292351751315',
    projectId: 'aha-project-management',
    storageBucket: 'aha-project-management.appspot.com',
    iosBundleId: 'com.example.ahaProjectManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBK9cx_j9NAZwib-81_lwJz0qU-8-y27cc',
    appId: '1:292351751315:ios:c328a53d7ba2c02ddd4966',
    messagingSenderId: '292351751315',
    projectId: 'aha-project-management',
    storageBucket: 'aha-project-management.appspot.com',
    iosBundleId: 'com.example.ahaProjectManagement.RunnerTests',
  );
}
